In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from IPython.display import Image
%matplotlib inline
import warnings
warnings.simplefilter('ignore')
import selenium
from selenium import webdriver
import csv
import time
import urllib
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,ElementNotInteractableException,ElementNotVisibleException,TimeoutException,ElementClickInterceptedException

In [163]:
# Main Page
# driver=webdriver.Chrome('chromedriver')
# driver.get('https://www.yatra.com/')
# driver.find_element_by_xpath('//input[@type="submit"]').click()
# driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
# # # Get scroll height after first time page load
# last_height = driver.execute_script("return document.body.scrollHeight")
# while True:
#      # Scroll down to bottom
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#      # Wait to load page
#     time.sleep(2)
#      # Calculate new scroll height and compare with last scroll height
#     new_height = driver.execute_script("return document.body.scrollHeight")
#     if new_height == last_height:
#         break
#     last_height = new_height

# driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + Keys.HOME)
# time.sleep(2)

# for i in driver.find_elements_by_xpath('//div[@class="flightItem border-shadow pr"]'):
#     i.find_element_by_xpath('div/div[2]/div/div/div/span').click()
#     time.sleep(1)
#     n=0
#     i=200
#     while n!=2:
#         driver.execute_script("window.scrollBy(0, arguments[0]);",i)
#         time.sleep(3)
#         n+=1
#         i+=100

In [165]:
#Calendar
# driver=webdriver.Chrome('chromedriver')
# driver.get('https://www.yatra.com/')
# driver.find_element_by_xpath('//input[@type="submit"]').click()
# driver.execute_script("window.scrollTo(0, 100)")
# time.sleep(5)
# driver.find_element_by_xpath('//p[@class="bold font-lightgrey fs-8 mt-2 text-uppercase"]').click()
# time.sleep(1)
# driver.find_element_by_xpath('//span[@class="ytfi-angle-right"]').click()
# for i in driver.find_elements_by_xpath('//div[@class="month-cal"]'):
#     i.find_element_by_xpath('table/tbody').click()
#     time.sleep(3)
#     driver.find_element_by_xpath('//p[@class="bold font-lightgrey fs-8 mt-2 text-uppercase"]').click()
#     time.sleep(2)
#     driver.find_element_by_xpath('//span[@class="ytfi-angle-right"]').click()

In [83]:
# a=[]
# for i in driver.find_elements_by_xpath('//div[@class="day-li text-center cursor-pointer pr active font-primary-color"]/p[1]'):
#     a.append(i.text)
# b=a*10
# b

In [114]:
30oct
Airline=[]
Date=[]
Source=[]
Destination=[]
Dep_Time=[]
Arrival_Time=[]
Duration=[]
Stops=[]
Price=[]
Date=[]
30 oct
driver=webdriver.Chrome('chromedriver')
driver.get('https://www.yatra.com/')
driver.find_element_by_xpath('//input[@type="submit"]').click()

source=["New Delhi","Mumbai","Bangalore","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
destination=["New Delhi","Bangalore","Mumbai","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
for i in source:
    search_s=driver.find_element_by_xpath('//input[@id="origin_0"]')
    search_s.clear()
    time.sleep(3)
    search_s.click()
    time.sleep(3)
    search_s.send_keys(i)
    time.sleep(2)
    for j in destination:
        search_d=driver.find_element_by_xpath('//input[@id="destination_0"]')
        search_d.clear()
        time.sleep(3)
        search_d.click()
        time.sleep(3)
        search_d.send_keys(j)
        time.sleep(5)
        if i==j:
            continue
            search_d.clear()
            time.sleep(3)
            search_d.send_keys(j)
            time.sleep(3)
        driver.find_element_by_xpath('//span[@class="radio v-aligm-t"]').click()           
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'//span[@ng-if="!submitted"]'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[2]/div'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
        # Scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                    # Wait to load page
            time.sleep(2)
                    # Calculate new scroll height and compare with last scroll height
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
        driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + Keys.HOME)
        time.sleep(2)
        for A,S,D,Dep,Ar,St,Du,P in zip(driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]/span'),
                                        driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p'),
                                        driver.find_elements_by_xpath('//div[@class="i-b pdd-0 text-left atime col-5"]/p[2]'),
                                        driver.find_elements_by_xpath('//div[@autom="departureTimeLabel"]'),
                                        driver.find_elements_by_xpath('//p[@autom="arrivalTimeLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]'),
                                        driver.find_elements_by_xpath('//p[@autom="durationLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')):
            Airline.append(A.text)
            Source.append(S.text)
            Destination.append(D.text)
            Dep_Time.append(Dep.text)
            Arrival_Time.append(Ar.text[:5])
            Stops.append(St.text)
            Duration.append(Du.text)
            Price.append(P.text)
        time.sleep(2)
for s in driver.find_elements_by_xpath('//div[@class="scroller full-width flex"]/ul/li[2]/div/p[1]'):
    Date.append(s.text[4:])
    z=len(Airline)
    Date=Date*z

In [115]:
d30=pd.DataFrame({})
d30['airline']=Airline
d30['source']=Source
d30['destination']=Destination
d30['deptime']=Dep_Time
d30['arrivtime']=Arrival_Time
d30['stops']=Stops
d30['duration']=Duration
d30['date']=Date
d30['price']=Price

In [116]:
d30

,airline,source,destination,deptime,arrivtime,stops,duration,date,price
0,Air Asia,New Delhi,Bangalore,15:40,20:35,1 Stop,4h 55m,30 Oct,"7,423"
1,Air Asia,New Delhi,Bangalore,12:40,18:20,1 Stop,5h 40m,30 Oct,"7,423"
2,Air Asia,New Delhi,Bangalore,14:30,20:35,1 Stop,6h 05m,30 Oct,"7,423"
3,Air Asia,New Delhi,Bangalore,11:55,18:20,1 Stop,6h 25m,30 Oct,"7,423"
4,Air Asia,New Delhi,Bangalore,07:10,13:55,1 Stop,6h 45m,30 Oct,"7,423"
...,...,...,...,...,...,...,...,...,...
5146,Air India,Lucknow,Bangalore,11:05,11:10,1 Stop,24h 05m,30 Oct,"14,499"
5147,Air India,Lucknow,Bangalore,08:55,10:25,2 Stop(s),25h 30m,30 Oct,"14,523"
5148,Air India,Lucknow,Bangalore,11:05,18:30,1 Stop,7h 25m,30 Oct,"14,919"
5149,Vistara,Lucknow,Bangalore,09:15,16:00,2 Stop(s),6h 45m,30 Oct,"15,905"
5150,Vistara,Lucknow,Bangalore,15:25,13:00,2 Stop(s),21h 35m,30 Oct,"18,258"

In [117]:
f="o30.csv"
d30.to_csv(f)

In [126]:
#31oct
Airline=[]
Date=[]
Source=[]
Destination=[]
Dep_Time=[]
Arrival_Time=[]
Duration=[]
Stops=[]
Price=[]
Date=[]
#30 oct
driver=webdriver.Chrome('chromedriver')
driver.get('https://www.yatra.com/')
driver.find_element_by_xpath('//input[@type="submit"]').click()

source=["New Delhi","Mumbai","Bangalore","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
destination=["New Delhi","Bangalore","Mumbai","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
for i in source:
    search_s=driver.find_element_by_xpath('//input[@id="origin_0"]')
    search_s.clear()
    time.sleep(3)
    search_s.click()
    time.sleep(3)
    search_s.send_keys(i)
    time.sleep(2)
    for j in destination:
        search_d=driver.find_element_by_xpath('//input[@id="destination_0"]')
        search_d.clear()
        time.sleep(3)
        search_d.click()
        time.sleep(3)
        search_d.send_keys(j)
        time.sleep(5)
        if i==j:
            continue
            search_d.clear()
            time.sleep(3)
            search_d.send_keys(j)
            time.sleep(3)
        driver.find_element_by_xpath('//span[@class="radio v-aligm-t"]').click()           
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'//span[@ng-if="!submitted"]'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[2]/div'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
        # Scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                    # Wait to load page
            time.sleep(2)
                    # Calculate new scroll height and compare with last scroll height
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
        driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + Keys.HOME)
        time.sleep(2)
        for A,S,D,Dep,Ar,St,Du,P in zip(driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]/span'),
                                        driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p'),
                                        driver.find_elements_by_xpath('//div[@class="i-b pdd-0 text-left atime col-5"]/p[2]'),
                                        driver.find_elements_by_xpath('//div[@autom="departureTimeLabel"]'),
                                        driver.find_elements_by_xpath('//p[@autom="arrivalTimeLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]'),
                                        driver.find_elements_by_xpath('//p[@autom="durationLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')):
            Airline.append(A.text)
            Source.append(S.text)
            Destination.append(D.text)
            Dep_Time.append(Dep.text)
            Arrival_Time.append(Ar.text[:5])
            Stops.append(St.text)
            Duration.append(Du.text)
            Price.append(P.text)
        time.sleep(2)
for s in driver.find_elements_by_xpath('//div[@class="scroller full-width flex"]/ul/li[2]/div/p[1]'):
    Date.append(s.text[4:])
    z=len(Airline)
    Date=Date*z

In [129]:
d31=pd.DataFrame({})
d31['airline']=Airline
d31['source']=Source
d31['destination']=Destination
d31['deptime']=Dep_Time
d31['arrivtime']=Arrival_Time
d31['stops']=Stops
d31['duration']=Duration
d31['date']=Date
d31['price']=Price

In [132]:
f='o31.csv'
d31.to_csv(f)

In [133]:
d31

,airline,source,destination,deptime,arrivtime,stops,duration,date,price
0,Air Asia,New Delhi,Bangalore,16:05,20:40,1 Stop,4h 35m,31 Oct,"7,423"
1,Air Asia,New Delhi,Bangalore,09:25,14:40,1 Stop,5h 15m,31 Oct,"7,423"
2,Air Asia,New Delhi,Bangalore,15:25,20:40,1 Stop,5h 15m,31 Oct,"7,423"
3,Air Asia,New Delhi,Bangalore,15:40,21:45,1 Stop,6h 05m,31 Oct,"7,423"
4,Air Asia,New Delhi,Bangalore,05:00,11:35,1 Stop,6h 35m,31 Oct,"7,423"
...,...,...,...,...,...,...,...,...,...
6854,Air India,Lucknow,Jaipur,17:20,09:20,1 Stop,16h 00m,31 Oct,"14,919"
6855,Air India,Lucknow,Jaipur,08:55,09:20,2 Stop(s),24h 25m,31 Oct,"16,707"
6856,Air India,Lucknow,Jaipur,08:55,09:20,2 Stop(s),24h 25m,31 Oct,"16,707"
6857,Air India,Lucknow,Jaipur,08:55,09:20,2 Stop(s),24h 25m,31 Oct,"16,707"
6858,Air India,Lucknow,Jaipur,17:20,07:10,2 Stop(s),13h 50m,31 Oct,"24,999"

In [146]:
#01 Nov
Airline=[]
Date=[]
Source=[]
Destination=[]
Dep_Time=[]
Arrival_Time=[]
Duration=[]
Stops=[]
Price=[]
Date=[]
#30 oct
driver=webdriver.Chrome('chromedriver')
driver.get('https://www.yatra.com/')
driver.find_element_by_xpath('//input[@type="submit"]').click()

source=["New Delhi","Mumbai","Bangalore","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
destination=["New Delhi","Bangalore","Mumbai","Chennai","Hyderabad","Goa","Kolkata","Pune","Jaipur","Lucknow"]
for i in source:
    search_s=driver.find_element_by_xpath('//input[@id="origin_0"]')
    search_s.clear()
    time.sleep(3)
    search_s.click()
    time.sleep(3)
    search_s.send_keys(i)
    time.sleep(2)
    for j in destination:
        search_d=driver.find_element_by_xpath('//input[@id="destination_0"]')
        search_d.clear()
        time.sleep(3)
        search_d.click()
        time.sleep(3)
        search_d.send_keys(j)
        time.sleep(5)
        if i==j:
            continue
            search_d.clear()
            time.sleep(3)
            search_d.send_keys(j)
            time.sleep(3)
        driver.find_element_by_xpath('//span[@class="radio v-aligm-t"]').click()           
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'//span[@ng-if="!submitted"]'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        try:
            WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.XPATH,'/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div'))).click()
        except NoSuchElementException as e:
            print(e)
        time.sleep(3)
        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
        # Scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                    # Wait to load page
            time.sleep(2)
                    # Calculate new scroll height and compare with last scroll height
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
        driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + Keys.HOME)
        time.sleep(2)
        for A,S,D,Dep,Ar,St,Du,P in zip(driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]/span'),
                                        driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p'),
                                        driver.find_elements_by_xpath('//div[@class="i-b pdd-0 text-left atime col-5"]/p[2]'),
                                        driver.find_elements_by_xpath('//div[@autom="departureTimeLabel"]'),
                                        driver.find_elements_by_xpath('//p[@autom="arrivalTimeLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]'),
                                        driver.find_elements_by_xpath('//p[@autom="durationLabel"]'),
                                        driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')):
            Airline.append(A.text)
            Source.append(S.text)
            Destination.append(D.text)
            Dep_Time.append(Dep.text)
            Arrival_Time.append(Ar.text[:5])
            Stops.append(St.text)
            Duration.append(Du.text)
            Price.append(P.text)
        time.sleep(2)
for s in driver.find_elements_by_xpath('//div[@class="scroller full-width flex"]/ul/li[3]/div/p[1]'):
    Date.append(s.text[4:])
    z=len(Airline)
    Date=Date*z

In [147]:
d01=pd.DataFrame({})
d01['airline']=Airline
d01['source']=Source
d01['destination']=Destination
d01['deptime']=Dep_Time
d01['arrivtime']=Arrival_Time
d01['stops']=Stops
d01['duration']=Duration
d01['date']=Date
d01['price']=Price

In [149]:
f='Nov1.csv'
d01.to_csv(f)

In [154]:
d01

,airline,source,destination,deptime,arrivtime,stops,duration,date,price
0,Air Asia,New Delhi,Bangalore,16:05,20:40,1 Stop,4h 35m,1 Nov,"7,423"
1,Air Asia,New Delhi,Bangalore,15:25,20:40,1 Stop,5h 15m,1 Nov,"7,423"
2,Air Asia,New Delhi,Bangalore,07:10,13:55,1 Stop,6h 45m,1 Nov,"7,423"
3,Air Asia,New Delhi,Bangalore,07:10,14:10,1 Stop,7h 00m,1 Nov,"7,423"
4,Air Asia,New Delhi,Bangalore,16:50,00:20,1 Stop,7h 30m,1 Nov,"7,423"
...,...,...,...,...,...,...,...,...,...
5658,Air India,Jaipur,New Delhi,10:15,20:35,1 Stop,10h 20m,1 Nov,"17,816"
5659,Air India,Jaipur,New Delhi,14:00,20:30,1 Stop,6h 30m,1 Nov,"20,756"
5660,Air India,Jaipur,New Delhi,14:00,10:15,1 Stop,20h 15m,1 Nov,"20,756"
5661,Air India,Jaipur,New Delhi,14:00,12:15,1 Stop,22h 15m,1 Nov,"20,756"
5662,Air India,Jaipur,New Delhi,14:00,19:20,2 Stop(s),29h 20m,1 Nov,"20,756"

In [155]:
d1=pd.read_csv('o30.csv')
d2=pd.read_csv('o31.csv')
d3=pd.read_csv('Nov1.csv')

In [156]:
df=pd.concat([d1,d2,d3])

In [157]:
df

,Unnamed: 0,airline,source,destination,deptime,arrivtime,stops,duration,date,price
0,0,Air Asia,New Delhi,Bangalore,15:40,20:35,1 Stop,4h 55m,30 Oct,"7,423"
1,1,Air Asia,New Delhi,Bangalore,12:40,18:20,1 Stop,5h 40m,30 Oct,"7,423"
2,2,Air Asia,New Delhi,Bangalore,14:30,20:35,1 Stop,6h 05m,30 Oct,"7,423"
3,3,Air Asia,New Delhi,Bangalore,11:55,18:20,1 Stop,6h 25m,30 Oct,"7,423"
4,4,Air Asia,New Delhi,Bangalore,07:10,13:55,1 Stop,6h 45m,30 Oct,"7,423"
...,...,...,...,...,...,...,...,...,...,...
5658,5658,Air India,Jaipur,New Delhi,10:15,20:35,1 Stop,10h 20m,1 Nov,"17,816"
5659,5659,Air India,Jaipur,New Delhi,14:00,20:30,1 Stop,6h 30m,1 Nov,"20,756"
5660,5660,Air India,Jaipur,New Delhi,14:00,10:15,1 Stop,20h 15m,1 Nov,"20,756"
5661,5661,Air India,Jaipur,New Delhi,14:00,12:15,1 Stop,22h 15m,1 Nov,"20,756"
5662,5662,Air India,Jaipur,New Delhi,14:00,19:20,2 Stop(s),29h 20m,1 Nov,"20,756"

In [158]:
f="Flight.xlsx"
df.to_excel(f)