In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import csv
import re
import time
import urllib
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,ElementNotInteractableException,ElementNotVisibleException,TimeoutException

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
    Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
    You need to find following details:
    A) Rank
    B) Name
    C) Artist
    D) Upload date
    E) Views

In [12]:
def scrap_you(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    values={
        "Rank":[],
        "Name":[],
        "Artist":[],
        "Upload Date":[],
        "Views":[]
    }
    for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr'):
        values['Rank'].append(i.find_element_by_xpath('td[1]').text)
        values['Name'].append(re.sub("\[.*?\]","",i.find_element_by_xpath('td[2]').text.replace('"',"")))
        values['Artist'].append(i.find_element_by_xpath('td[3]').text)
        values['Views'].append(i.find_element_by_xpath('td[4]').text)
        values['Upload Date'].append(i.find_element_by_xpath('td[5]').text)
    return values

df=scrap_you(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
pd.DataFrame(df)

,Rank,Name,Artist,Upload Date,Views
0,1.,Baby Shark Dance,Pinkfong Kids' Songs & Stories,"June 17, 2016",8.91
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.43
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.53
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.37
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.16
5,6.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.44
6,7.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.26
7,8.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.22
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.22
9,10.,Gangnam Style,Psy,"July 15, 2012",4.11
10,11.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",3.97
11,12.,Sugar,Maroon 5,"January 14, 2015",3.50
12,13.,Sorry,Justin Bieber,"October 22, 2015",3.45
13,14.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.43
14,15.,Roar,Katy Perry,"September 5, 2013",3.38
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.33
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.28
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.13
18,19.,Dark Horse,Katy Perry,"February 20, 2014",3.10
19,20.,Faded,Alan Walker,"December 3, 2015",3.09
20,21.,Shake It Off,Taylor Swift,"August 18, 2014",3.07
21,22.,Girls Like You,Maroon 5,"May 31, 2018",3.06
22,23.,Lean On,Major Lazer,"March 22, 2015",3.06
23,24.,Bailando,Enrique Iglesias,"April 11, 2014",3.06
24,25.,Let Her Go,Passenger,"July 25, 2012",3.02
25,26.,Mi Gente,J Balvin,"June 29, 2017",2.94
26,27.,Perfect,Ed Sheeran,"November 9, 2017",2.89
27,28.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.87
28,29.,Axel F,Crazy Frog,"June 16, 2009",2.86
29,30.,Hello,Adele,"October 22, 2015",2.85

2. Scrape the details team India’s international fixtures from bcci.tv.
    Url = https://www.bcci.tv/.
    You need to find following details:
    A) Match title (I.e. 1st ODI)
    B) Series
    C) Place
    D) Date
    E) Time
    Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [15]:
def scrap_bcc(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    driver.find_element_by_xpath('//div[@class="navigation__drop-down drop-down drop-down--reveal-on-hover"]').click()
    driver.find_element_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]').click()
    time.sleep(2)
    values={
        'Title':[],
        'Series':[],
        'Place':[],
        'Date':[],
        'Time':[]
    }
    for t,s,p,d,ti in zip(driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]'),
                         driver.find_elements_by_xpath('//div[@class="fixture__teams"]'),
                         driver.find_elements_by_xpath('//div[@class="fixture__description u-unskewed-text"]/p/span'),
                         driver.find_elements_by_xpath('//div[@class="fixture__full-date"]'),
                          driver.find_elements_by_xpath('//span[@class="fixture__time"]')):
        values['Title'].append(t.text)
        values['Series'].append(s.text.replace('\n'," "))
        values['Place'].append(p.text)
        dates=d.text.split("\n")[:2]
        values['Date'].append('-'.join(dates))
        values['Time'].append(ti.text)
    return values
df=scrap_bcc(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://www.bcci.tv/")
pd.DataFrame(df)

,Title,Series,Place,Date,Time
0,1st ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",13-JULY,14:30 IST
1,2nd ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",16-JULY,14:30 IST
2,3rd ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",18-JULY,14:30 IST
3,1st T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",21-JULY,19:00 IST
4,2nd T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",23-JULY,19:00 IST
5,3rd T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",25-JULY,19:00 IST
6,1st Test,ENGLAND v INDIA,"Trent Bridge, Nottingham",04-AUGUST,15:30 IST
7,2nd Test,ENGLAND v INDIA,"Lord's, London",12-AUGUST,15:30 IST
8,3rd Test,ENGLAND v INDIA,"Headingley, Leeds",25-AUGUST,15:30 IST
9,4th Test,ENGLAND v INDIA,"The Oval, London",02-SEPTEMBER,15:30 IST
10,5th Test,ENGLAND v INDIA,"Old Trafford, Manchester",10-SEPTEMBER,15:30 IST

3. Scrape the details of selenium exception from guru99.com.
    Url = https://www.guru99.com/
    You need to find following details:
    A) Name
    B) Description

In [3]:
def scrap_selenium_exceptions(path,web):
    driver = webdriver.Chrome(path)
    driver.get(web)
    time.sleep(2)
    driver.find_element_by_id('java_technologies').find_element_by_xpath("li[3]").click()
    driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']").click()
    values={
        "Name":[],
        "Description":[]}
    for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr"):
        try:
            i.find_element_by_xpath("td/strong").text
        except NoSuchElementException as e:
            values["Name"].append(i.text.split(" ")[0])
            values['Description'].append(' '.join(i.text.split(" ")[1:]))
    return values
data=scrap_selenium_exceptions(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://www.guru99.com/")
pd.DataFrame(data)

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
    Url = http://statisticstimes.com/
    You have to find following details:
    A) Rank
    B) State
    C) GSDP at current price (19-20)
    D) GSDP at current price (18-19)
    E) Share(18-19)
    F) GDP($ billion)

In [15]:
def scrap_stat(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    driver.get(driver.find_element_by_xpath('//div[@class="navbar"]/div[2]/div/a[3]').get_attribute('href'))
    driver.find_element_by_xpath('//div[@style="float:left;background-color:seashell;width:400px;height:800px;"]/ul/li/a').click()
    values={
        'Rank':[],
        'State':[],
        'GSDP20':[],
        'GSDP19':[],
        'Share':[],
        'GDP':[]
    }
    for a,b,c,d,e,f in zip (driver.find_elements_by_xpath('//td[@class="data1"]'),
                           driver.find_elements_by_xpath('//td[2][@class="name"]'),
                           driver.find_elements_by_xpath('//td[3][@class="data"]'),
                           driver.find_elements_by_xpath('//td[4][@class="data sorting_1"]'),
                           driver.find_elements_by_xpath('//td[5][@class="data"]'),
                           driver.find_elements_by_xpath('//td[6][@class="data"]')):
        values['Rank'].append(a.text)
        values['State'].append(b.text)
        values['GSDP20'].append(c.text)
        values['GSDP19'].append(d.text)
        values['Share'].append(e.text)
        values['GDP'].append(f.text)
    return values
df=scrap_stat(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","http://statisticstimes.com/")
pd.DataFrame(df)

   Rank              State     GSDP20     GSDP19   Share      GDP
0     1        Maharashtra          -  2,632,792  13.94%  399.921
1     2         Tamil Nadu  1,845,853  1,630,208   8.63%  247.629
2     3      Uttar Pradesh  1,687,818  1,584,764   8.39%  240.726
3     4            Gujarat          -  1,502,899   7.96%  228.290
4     5          Karnataka  1,631,977  1,493,127   7.91%  226.806
..  ...                ...        ...        ...     ...      ...
61   28            Manipur     29,148     25,141   0.15%   18,549
62   29             Sikkim     28,391     24,534   0.15%   17,060
63   30           Nagaland          -     22,488   0.15%        -
64   31  Arunachal Pradesh          -     20,947   0.13%        -
65   32            Mizoram     24,424          -   0.13%   17,797

[66 rows x 6 columns]

5. Scrape the details of trending repositories on Github.com.
    Url = https://github.com/
    You have to find the following details:
    A) Repository title
    B) Repository description
    C) Contributors count
    D) Language used

In [2]:
def scrap_github_data(path,web_link):
    driver = webdriver.Chrome(path)
    driver.get(web_link)
    time.sleep(1)
    driver.get(driver.find_element_by_xpath("//ul[@class='list-style-none mb-3']/li[3]/a").get_attribute("href"))
    values={
        "Repository title":[],
        "Repository description":[],
        "Contributors count":[],
        "Language used":[]}
    for title,desc,count,lang in zip(driver.find_elements_by_xpath("//span[@class='text-normal']"), 
                                     driver.find_elements_by_xpath("//p[@class='col-9 color-text-secondary my-1 pr-4']"), 
                                     driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']/a[2]"),
                                     driver.find_elements_by_xpath("//span[@itemprop='programmingLanguage']")):
        values['Repository title'].append(title.text.split()[0])
        values['Repository description'].append(desc.text)
        values['Contributors count'].append(count.text)
        values['Language used'].append(lang.text)
    return values
data=scrap_github_data(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://github.com/")
pd.DataFrame(data)

,Repository title,Repository description,Contributors count,Language used
0,bndw,📶 Print a QR code for connecting to your WiFi,117,JavaScript
1,facebook,An open-source C++ library developed and used ...,"4,142",C++
2,microsoft,"12 Weeks, 24 Lessons, IoT for All!",290,C++
3,NationalSecurityAgency,Ghidra is a software reverse engineering (SRE)...,"3,619",Java
4,microsoft,Linux OS for Azure 1P services and edge applia...,89,Go
5,opensearch-project,Open source distributed and RESTful search eng...,253,Java
6,avelino,"A curated list of awesome Go frameworks, libra...","8,657",Go
7,fenixsoft,讨论如何构建一套可靠的大型分布式系统,223,Vue
8,dromara,这可能是史上功能最全的Java权限认证框架！目前已集成——登录认证、权限认证、分布式Sess...,781,Java
9,0vercl0k,"wtf is a distributed, code-coverage guided, cu...",25,C++
10,TencentARC,"12 weeks, 24 lessons, classic Machine Learning...",78,Python
11,microsoft,专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！,"2,642",Jupyter Notebook
12,chefyuan,End-to-end image segmentation kit based on Pad...,"1,130",Java
13,PaddlePaddle,微信消息解密工具,438,Python
14,JustYoomoon," Now we have become very big, Different from ...",30,C++
15,jaywcjlove,🇨🇳 GitHub中文排行榜，帮助你发现高分优秀中文项目、更高效地吸收国人的优秀经验成果；榜...,"4,832",JavaScript
16,kon9chunkit,Used to integrate the Facebook Platform with y...,"5,139",Java
17,facebook,A Go framework for microservices.,"2,860",Objective-C
18,go-kratos,A cat(1) clone with wings.,"2,807",Go
19,sharkdp,This repository contains all the DSA (Data-Str...,720,Rust
20,Aaron-lv,Model parallel transformers in JAX and Haiku,44,Jupyter Notebook
21,AkashSingh3031,An open source vector database powered by Fais...,566,Python

6. Scrape the details of top 100 songs on billboard.com.
    Url = https://www.billboard.com/
    You have to find the following details:
    A) Song name
    B) Artist name
    C) Last week rank
    D) Peak rank
    E) Weeks on board

In [8]:
def scrap_song(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    driver.get(driver.find_element_by_xpath('//div[@class="header__sticky__child"]/nav/ul/li[3]/a').get_attribute('href'))
    time.sleep(3)
    values={
        'Song':[],
        'Artist':[],
        'Week':[],
        'Peak':[],
        'Chart':[]
    }
    for a,b,c,d,e in zip(driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]'),
                         driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]'),
                         driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]'),
                         driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]'),
                         driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')):
        values['Song'].append(a.text)
        values['Artist'].append(b.text)
        values['Week'].append(c.text)
        values['Peak'].append(d.text)
        values['Chart'].append(e.text)
    return values
df=scrap_song(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://www.billboard.com/")
pd.DataFrame(df)

,Song,Artist,Week,Peak,Chart
0,Butter,BTS,1,1,7
1,Good 4 U,Olivia Rodrigo,2,1,8
2,Levitating,Dua Lipa Featuring DaBaby,4,2,40
3,Kiss Me More,Doja Cat Featuring SZA,3,3,13
4,Montero (Call Me By Your Name),Lil Nas X,8,1,15
...,...,...,...,...,...
95,All I Know So Far,P!nk,-,74,4
96,What's Next,Drake,-,1,16
97,Enough For You,Olivia Rodrigo,-,14,6
98,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
99,Tell Em,Cochise & $NOT,-,64,4

7. Scrape the details of Data science recruiters from naukri.com.
    Url = https://www.naukri.com/
    You have to find the following details:
    A) Name
    B) Designation
    C) Company
    D) Skills they hire for
    E) Location
    Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
    click on search. All this should be done through code

In [3]:
def scrap_job_data_sci_nkry(path,web_link):
    driver = webdriver.Chrome(path)
    driver.get(web_link)
    driver.get(driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute('href'))
    driver.find_element_by_xpath("//input[@class='sugInp']").send_keys("Data Science")
    driver.find_element_by_id("qsbFormBtn").click()
    data=[]
    data.append(["Name","Designation","Company","Location","Skills they hire for"])
    for i in driver.find_elements_by_xpath("//div[@class='recInfo']"):
        row=i.text.split("\n")
        row.pop(4)
        data.append(row[:5])
    return data
data=scrap_job_data_sci_nkry(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://www.naukri.com/")
pd.DataFrame(data[1:],columns=data[0])

,Name,Designation,Company,Location,Skills they hire for
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
11,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
20,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
21,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
23,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
25,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,Skills/Roles I hire for :,1 active jobs | Last active on 10-Oct-2017
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
28,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
32,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
33,Prateek Kumar,Head,Trisect,Noida,"Java, Python, Angularjs, Software Testing, Mac..."
34,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
35,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
40,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
43,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
45,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
46,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
47,Amir Chowdhury,Managing Partner,Granular.ai,Skills/Roles I hire for :,2 active jobs | Last active on 04-Nov-2016
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,Noida,"consulting, Education Counseling, Educational ..."
49,Sunny Sharma,Managing Director - HR,Western Service Providers,Mumbai,"Software Professionals, Engineering, Technical..."

8. Scrape the details of Highest selling novels.
    Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
    You have to find the following details:
    A) Book name
    B) Author name
    C) Volumes sold
    D) Publisher
    E) Genre

Error in loading of Website

9. Scrape the details most watched tv series of all time from imdb.com.
    Url = https://www.imdb.com/list/ls095964455/
    You have to find the following details:
    A) Name
    B) Year span
    C) Genre
    D) Run time
    E) Ratings
    F) Votes

In [6]:
def scrap_imdb(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    values={
        'Name':[],
        'Year':[],
        'Genre':[],
        'Runtime':[],
        'Ratings':[],
        'Votes':[]
    }
    for a,b,c,d,e,f in zip( driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/a'),
                           driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/span[2]'),
                           driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[5]'),
                           driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[3]'),
                            driver.find_elements_by_xpath('//span[@class="ipl-rating-star__rating"]'),
                           driver.find_elements_by_xpath('//span[@name="nv"]')):
        values['Name'].append(a.text)
        values['Year'].append(b.text)
        values['Genre'].append(c.text)
        values['Runtime'].append(d.text)
        values['Ratings'].append(e.text)
        values['Votes'].append(f.text)
    return values
df=scrap_imdb(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://www.imdb.com/list/ls095964455/")
pd.DataFrame(df)

,Name,Year,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,835,393"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,,"874,161"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,Rate,"879,319"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,,"264,212"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,,"225,709"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,,"44,790"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,,"55,397"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,,"169,584"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,,"35,120"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,,"193,351"

10. Details of Datasets from UCI machine learning repositories.
    Url = https://archive.ics.uci.edu/
    You have to find the following details:
    A) Dataset name
    B) Data type
    C) Task
    D) Attribute type
    E) No of instances
    F) No of attribute
    G) Year
    Note: - from the home page you have to go to the Show All Dataset page through code

In [11]:
def scrap_uci(path,web):
    driver=webdriver.Chrome(path)
    driver.get(web)
    driver.find_element_by_xpath('//span[@class="whitetext"]/a/font/b').click()
    data=[]
    for i in driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr'):
        data.append(i.text.split("\n"))
    return data
df=scrap_uci(r"C:\Users\veenu\Downloads\chromedriver_win32\chromedriver.exe","https://archive.ics.uci.edu/")
pd.DataFrame(data[1:],columns=data[0])

,Name,Designation,Company,Location,Skills they hire for
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
11,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
20,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
21,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
23,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
25,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,Skills/Roles I hire for :,1 active jobs | Last active on 10-Oct-2017
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
28,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
32,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
33,Prateek Kumar,Head,Trisect,Noida,"Java, Python, Angularjs, Software Testing, Mac..."
34,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
35,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
40,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
43,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
45,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
46,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
47,Amir Chowdhury,Managing Partner,Granular.ai,Skills/Roles I hire for :,2 active jobs | Last active on 04-Nov-2016
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,Noida,"consulting, Education Counseling, Educational ..."
49,Sunny Sharma,Managing Director - HR,Western Service Providers,Mumbai,"Software Professionals, Engineering, Technical..."